import{$,esc,money,layout,toast}from"./core.js";
layout("home");const sb=window.sky.sb;
function favs(){return JSON.parse(localStorage.getItem("skyfit_favs")||"[]")}
function toggleFav(id){let a=favs();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem("skyfit_favs",JSON.stringify(a));toast("Sevimlilər yeniləndi");loadProducts()}
window.toggleFav=toggleFav;
async function loadProducts(){const root=$("#products");if(!root)return;if(!sb){root.innerHTML=`<div class="empty">Supabase qoşulmayıb. setup.html səhifəsinə baxın.</div>`;return}const{data,error}=await sb.from("products").select("*").eq("is_active",true).eq("show_public",true).order("name");if(error){root.innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}const f=favs();root.innerHTML=(data||[]).map(p=>`<article class="card product-card neon"><button class="fav" onclick="toggleFav('${p.id}')">${f.includes(p.id)?"♥":"♡"}</button><img src="${esc(p.image_url||"assets/img/logo.png")}" alt="${esc(p.name)}"><div class="product-body"><div class="product-meta"><div><h3>${esc(p.name)}</h3><span class="muted">${esc(p.description||p.stock_unit)}</span></div><div class="price">${money(p.retail_price)}</div></div><div class="split" style="margin-top:12px"><span class="badge ${Number(p.stock_quantity)>0?"ok":"danger"}">${Number(p.stock_quantity)>0?"Stokda":"Bitib"}</span><a class="btn btn-sm" href="https://wa.me/${window.sky.cfg.BUSINESS.whatsapp}?text=${encodeURIComponent(p.name+" sifariş etmək istəyirəm")}" target="_blank">Sifariş</a></div></div></article>`).join("")||`<div class="empty">Məhsul əlavə edilməyib.</div>`}
async function loadTrainers(){const root=$("#trainers");if(!root||!sb)return;const{data}=await sb.from("trainers").select("*").eq("is_active",true).order("sort_order");root.innerHTML=(data||[]).map(t=>`<article class="card neon"><img src="${esc(t.image_url||"assets/img/logo.png")}" style="height:280px;width:100%;object-fit:cover;border-radius:14px"><h3>${esc(t.full_name)}</h3><p class="muted">${esc(t.specialty||"Fitnes məşqçisi")}</p></article>`).join("")}
loadProducts();loadTrainers();
if(sb)sb.channel("public-products").on("postgres_changes",{event:"*",schema:"public",table:"products"},loadProducts).subscribe();
