import{$,esc,money,fmtDate,statusBadge,requireAuth,layout,toast,uploadPublic}from"./core.js";
layout("profile");const sb=window.sky.sb;let me;
async function load(){me=await requireAuth();if(!me)return;$("#profileName").textContent=me.full_name||"Üzv";$("#profileEmail").textContent=me.email||"";$("#avatar").src=me.avatar_url||"assets/img/logo.png";$("#profileForm").full_name.value=me.full_name||"";$("#profileForm").phone.value=me.phone||"";$("#profileForm").birth_date.value=me.birth_date||"";$("#profileForm").address.value=me.address||"";
const[{data:m},{data:d},{data:sales}]=await Promise.all([sb.from("memberships").select("*,membership_plans(name,price,duration_days)").eq("member_id",me.id).order("end_date",{ascending:false}).limit(1),sb.from("debt_accounts").select("*").eq("member_id",me.id).maybeSingle(),sb.from("sales").select("id,total_amount,created_at,payment_status").eq("member_id",me.id).order("created_at",{ascending:false}).limit(8)]);
const mm=m?.[0];$("#membership").innerHTML=mm?`<div class="card neon"><div class="split"><div><span class="muted">Cari abunəlik</span><h2>${esc(mm.membership_plans?.name||"Plan")}</h2></div>${statusBadge(mm.end_date)}</div><p>${fmtDate(mm.start_date)} — ${fmtDate(mm.end_date)}</p></div>`:`<div class="notice danger">Aktiv abunəliyiniz yoxdur.</div>`;
$("#debt").innerHTML=`<div class="card ${Number(d?.balance)>0?"neon":""}"><span class="muted">Cari borc</span><div class="stat-value" style="color:${Number(d?.balance)>0?"var(--danger)":"var(--success)"}">${money(d?.balance||0)}</div></div>`;
$("#history").innerHTML=(sales||[]).map(x=>`<tr><td>${fmtDate(x.created_at)}</td><td>${money(x.total_amount)}</td><td><span class="badge">${esc(x.payment_status)}</span></td></tr>`).join("")||`<tr><td colspan="3" class="empty">Alış tarixçəsi yoxdur.</td></tr>`}
$("#profileForm")?.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);let avatar=me.avatar_url;if(f.get("avatar")?.size)avatar=await uploadPublic("avatars",f.get("avatar"),me.id);const {error}=await sb.from("profiles").update({full_name:f.get("full_name"),phone:f.get("phone"),birth_date:f.get("birth_date")||null,address:f.get("address"),avatar_url:avatar}).eq("id",me.id);if(error)toast(error.message,"error");else{toast("Profil yeniləndi","success");load()}});
load();
